### ISSUE TITLE
http://yugioh.wikia.com/wiki/

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#2569] opened 2016-12-21 05:11 UTC

**Comment by uBlock-user** [comment] 2016-12-21 14:51
add

````
/abtesting/
@@||wikia.com^$elemhide
````

**Comment by noirscape** [comment] 2016-12-28 14:28
duplicate of #2557.

**Comment by Hello23-Ygopro** [comment] 2017-02-02 07:25
Sorry for the late reply..
Wow thanks alot , it worked like a charm !

**Closed as completed by Hello23-Ygopro** 2017-02-02 07:25 UTC
