### ISSUE TITLE
aranzulla.it

### ISSUE THREAD

**Issue by NessunoIM** [reek/anti-adblock-killer#1619] opened 2016-06-20 23:57 UTC
Site:http://www.aranzulla.it

![aran](https://cloud.githubusercontent.com/assets/19640640/16213911/6514e8ee-3753-11e6-81e5-f941d75732b4.png)
Mozilla Firefox 47
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by giampi75** [comment] 2016-06-21 06:18
I confirm: since this morning Aranzulla is blocked. In the past days, anti-adblok-killer did work perfectly

**Comment by Blelle** [comment] 2016-06-21 09:18
![immagine](https://cloud.githubusercontent.com/assets/17627130/16224341/ea9e86de-37a1-11e6-96f7-24f7c2fa3058.png)

lol

**Comment by giampi75** [comment] 2016-06-22 06:12
This morning:

![aran](https://cloud.githubusercontent.com/assets/17108055/16256252/14bf58bc-3851-11e6-912a-4771e0362cb4.jpg)

**Comment by sxit07** [comment] 2016-06-22 16:34
Same problem for me:
http://www.aranzulla.it/locked-firefox.html?p=37075&m=file
[url=http://imgur.com/zVE2Ur6][img]http://i.imgur.com/zVE2Ur6.png[/img][/url]
Mozilla Firefox 47
Greasemonkey
Adblock Plus
EasyList + AakList + ABP X Files

**Comment by reek** [comment] 2016-06-23 17:57
Ok, I'll kill it, thanks

**Comment by PeopleInside** [comment] 2016-06-24 09:06
Now seems they add a more powerful block who not let you read nothing if you not disable adblock.

**Comment by giampi75** [comment] 2016-06-24 14:16
I confirm, PeopleInside

**Comment by Robotex** [comment] 2016-06-25 13:03
This should do

     aranzulla_it : {
        host : ['www.aranzulla.it'],
        onBeforeScript : function () {
          return [{
              contains : 'abCheck.init',
              external : false,
              remove : true
            }
          ];
        }
      },

**Comment by giampi75** [comment] 2016-06-26 19:28
The Robotex's solution works for me. Thanks a lot

**Comment by PeopleInside** [comment] 2016-06-26 19:31
How to use the Robotex's solution?

**Comment by giampi75** [comment] 2016-06-26 19:51
Devi copiarlo nello script che trovi nel tuo profilio firefox. Lo apri, cerchi la sezione con le parti dedicate ai singoli siti (io non ci capisco molto, ma ho fatto così) e copi integralmente la parte di script data da Robotex

**Comment by PeopleInside** [comment] 2016-06-26 19:56
Io non ci riesco ^_^ I Am Unable to do :)

**Comment by Robotex** [comment] 2016-06-26 20:07
Come ha detto giampi75 devi semplicemente cercare nello [script](https://github.com/reek/anti-adblock-killer/raw/master/anti-adblock-killer.user.js) la riga `blogspot : { ` e prima di esso aggiungere il pezzo di codice che ho scritto.

**Comment by giampi75** [comment] 2016-06-26 20:08
You must open the anti-adblock-killer.user.js file with, i.e., the Notepad. And you insert the lines created by Robotex

**Comment by PeopleInside** [comment] 2016-06-26 20:29
Grazie :D

**Comment by NessunoIM** [comment] 2016-06-26 23:52
Perfetto, funziona! :D

**Comment by Blelle** [comment] 2016-06-27 08:27
By the way maybe there isn't anymore an antiblock because i tried to open an link with only adblock activated and i don't had no problems to read the article

**Comment by PeopleInside** [comment] 2016-06-27 08:28
Is active the antiadblock. Happy you resolved. I try and is active just use a browser without anti adblock

**Comment by sxit07** [comment] 2016-06-27 13:27
It works for me.

@Robotex: thank you very much!

**Comment by PeopleInside** [comment] 2016-06-30 20:46
Seems the website has edited the anti adblock and previous solution is not working anymore. Intelligent the webmaster.

**Comment by Robotex** [comment] 2016-06-30 21:23
Non mi risulta

**Comment by PeopleInside** [comment] 2016-06-30 21:29
Già, forse sono io che faccio confusione. Nemmeno a me ora. Boh, scusate.

**Comment by giampi75** [comment] 2016-06-30 21:32
This evening at 23:31:
![aran](https://cloud.githubusercontent.com/assets/17108055/16504949/ea2b7cfe-3f1a-11e6-811b-8c5f4f18e049.jpg)

**Comment by PeopleInside** [comment] 2016-06-30 21:39
@giampi75 Giampi75 maybe you clicked a wrong URL.
Are you sure you are surfing with the right protected browser?
Please try to open this URL: http://www.aranzulla.it/immagini-per-whatsapp-63009.html from the correct browser you should see article without problem.

I see one link in this post point to the anti adblock page.

Was my error, the fix seems continue to work well.

**Comment by sxit07** [comment] 2016-06-30 22:12
No problems for me!
The fix continues to work well.

**Comment by giampi75** [comment] 2016-07-01 06:14
@Peopleinside That's true! Sorry

**Comment by giampi75** [comment] 2016-07-06 09:17
Today....

![aran](https://cloud.githubusercontent.com/assets/17108055/16613176/2e6d1824-436b-11e6-9246-3a39e3230e2e.jpg)

**Comment by PeopleInside** [comment] 2016-07-06 09:23
Yes is not working anymore.

**Comment by Robotex** [comment] 2016-07-06 12:36
aranzulla_it : {
        host : ['aranzulla.it'],
        onBeforeScript : function () {
          return [{
              contains : 'navigator.userAgent||navigator.vendor||window.opera',
              external : false,
              remove : true
            }
          ];
        }
      },

consiglio caldamente l'uso di NoScript

**Comment by giampi75** [comment] 2016-07-06 13:35
Funziona con NoScript

**Comment by sxit07** [comment] 2016-07-06 14:37
The new fix of Robotex works well for me.

@Robotex: thank you very much!

**Comment by reek** [comment] 2016-07-06 16:52
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by sxit07** [comment] 2016-07-07 17:09
With the last fix of Robotex I had not problems.

Now with the updates of the userscript and of the filterlist, the problem is back:
http://www.aranzulla.it/locked-firefox.php?p=31819&fabm=file&rnd=0.9626968235918991
![screenshot](https://cloud.githubusercontent.com/assets/18562965/16662121/41432eb4-4476-11e6-8e93-48b81fa13eed.png)
Mozilla Firefox 47
Greasemonkey
Adblock Plus
EasyList + AakList + ABP X Files

**Comment by PeopleInside** [comment] 2016-07-07 17:12
Try to use No Script: https://addons.mozilla.org/it/firefox/addon/noscript/ and the aranzulla website will work

**Comment by reek** [comment] 2016-07-08 00:13
@sxit07 
Ok, I'll add @Robotex patch

**Comment by reek** [comment] 2016-07-08 00:14
@Robotex 
Thanks :+1:

**Comment by sxit07** [comment] 2016-07-12 07:19
I don't want to install another extension.
So I modified again the script with Robotex's fix.
It works well ( @Robotex: thank you again).
@reek: I wait for the new version of the script

**Comment by Alessandro-Barbieri** [comment] 2016-07-29 21:06
I think is still blocking www.aranzulla.it%2Fcome-virtualizzare-una-macchina-fisica-24060.html

**Comment by mapx-** [comment] 2016-07-29 21:12
add these filters in your adblocker:
```
@@|http://*$script,xmlhttprequest,image,subdocument,domain=aranzulla.it
aranzulla.it##.banner.adsbygoogle
aranzulla.it##.adsbygoogle
```

**Comment by Fr3ddohh** [comment] 2016-08-06 18:48
Come ha detto PeopleInside, se vuoi una soluzione immediata ma svantaggiosa c'è **NoScript** per Firefox (https://addons.mozilla.org/it/firefox/addon/noscript/) o **NoScript Suite Lite** per Chrome (https://chrome.google.com/webstore/detail/no-script-suite-lite/ahnanjpbkghcdgmlchbcfoiefnifjeni?hl=it)

Like PeopleInside, if you want an immediate solution download **NoScript** for Firefox or **NoScript Suite Lite** for Chrome.

**Comment by Robotex** [comment] 2016-08-07 12:56
Su Firefox c'è anche YesScript che si comporta da blacklist di default, così da poter disattivare javascript solo su alcuni domini specifici.

**Comment by Alessandro-Barbieri** [comment] 2016-08-17 01:42
@mapx- it works!

**Comment by Fr3ddohh** [comment] 2016-09-10 20:55
I've seen another adblock, that doesn't got blocked by anti-adblock scripts. It's called Disconnect.me.

**Comment by NessunoIM** [comment] 2016-09-18 22:40
Robotex solution is perfect! YesScript <3

**Comment by giampi75** [comment] 2016-10-29 08:21
Today.....

![aran](https://cloud.githubusercontent.com/assets/17108055/19828240/7f499a1e-9dc1-11e6-9632-fcebd45873da.jpg)

**Comment by mapx-** [comment] 2016-10-29 08:30
don't use yesscript, but add these filters
```
@@||rnzll.it^
@@|http://$image,domain=aranzulla.it
```

**Comment by giampi75** [comment] 2016-10-29 09:18
It doesn't works for me and I don't have yesscript

Firefox 49.0.1
Greasemonkey
Ubo

**Comment by mapx-** [comment] 2016-10-29 09:22
tested in ubo, all fine for me (easylist, easyprivacy, easy italy, peter lowe)
If you are using other blocking addons disable them (ghostery, disconnect ...)

**Comment by Robotex** [comment] 2016-10-29 10:52
ubo has committed a [rule](https://github.com/uBlockOrigin/uAssets/commit/dc9dbb6baba93c4fd5fb53424177d07b3af988ba) that blocks it, also their new [cosmetic filters section](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#has) is definitely a good read

**Comment by giampi75** [comment] 2016-10-29 16:53
Thanks to all. I didn't have easylist italy. Now it works

**Comment by sxit07** [comment] 2016-11-09 16:47
Is there any workable solution for Adblock Plus o Anti-Adblock Killer?

**Comment by mapx-** [comment] 2016-11-09 17:11
even disabling completely ABP the warning message is still present, so they broke their own site

**Comment by mapx-** [comment] 2016-11-09 17:12
add these filters
```
@@||rnzll.it^
@@|http://$image,domain=aranzulla.it
@@||hotpornfile.org^$generichide
@@||pagead2.googlesyndication.com^$domain=aranzulla.it
```

**but you have to disable reek userscript**

**Comment by sxit07** [comment] 2016-11-09 17:57
@mapx-: thank you very much!
It works!

Is there a way to disable AAK Reek's userscript only a specific site (aranzulla.it)?

**Comment by mapx-** [comment] 2016-11-09 18:00
You have to edit the userscript, then add an exclusion row like:

// @exclude  *aranzulla.it*

**Comment by sxit07** [comment] 2016-11-10 09:34
@mapx-: you are great! Thank you for the answer.

I expect reek's update...

**Comment by reek** [comment] 2016-11-17 03:18
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Closed by reek** 2016-11-17 03:18 UTC
Labels: AakScript, BlockAdBlock, Request

**Comment by DjDiabolik** [comment] 2017-04-10 22:42
Hi boys... i have a very strange problems.... i have setup chrome (portable) to my windows and i have installed:
Tampermonkey whit Userscript
Adblock Plus whit Filterlist
On Adblock Plus i have also installed EasyList, EasyList Italy and EasyPrivacy

I have the same exact setup also on firefox.... and whit firefox i can read all article whitout any problems but on chrome no:
When i open an article (also i have tryed to open same article on chrome and firefox at sametime) on firefox i can read but on chrome after about 10 seconds i obtain the errors says "Blocked Article" for read the article activate the javascript or disable Adblock".

It's very strange because, i already say, on firefox i have the same exact addons/script and aranzulla.it working whitout any problems.... it's normal ?
