### ISSUE TITLE
linkdrop.net

### ISSUE THREAD

**Issue by zepheria** [reek/anti-adblock-killer#324] opened 2015-04-21 13:32 UTC
http://linkdrop.net/zcPyH
http://i.imgur.com/8prA4mq.png
Chrome
Tampermonkey
AdBlock, AdBlock Plus
EasyList

thanks!

**Comment by vinctux** [comment] 2015-04-21 14:12
The problem is this:
```javascript
(function() {
    var message = "We've detected that you have an ad blocker enabled! Please add linkdrop.net to your ad blocking WHITELIST or disable it and help support our work! Thank you!";

        // Define a function for showing the message.
        // Set a timeout of 2 seconds to give adblocker
        // a chance to do its thing
        var tryMessage = function() {
            setTimeout(function() {
                if(!document.getElementsByClassName) return;
                var ads = document.getElementsByClassName('afs_ads'),
                    ad  = ads[ads.length - 1];

                if(!ad
                    || ad.innerHTML.length == 0
                    || ad.clientHeight === 0) {
                    alert(message);
                    window.location.href = '//go.pub2srv.com/afu.php?zoneid=245654';
                } else {
                    ad.style.display = 'none';
                }

            }, 2000);
        }

        /* Attach a listener for page load ... then show the message */
        if(window.addEventListener) {
            window.addEventListener('load', tryMessage, false);
        } else {
            window.attachEvent('onload', tryMessage); //IE
        }
})();
```
As it seems it's an honeypot for AdBlockers:
```html
<div class="afs_ads">&nbsp;</div>
```

**Comment by reek** [comment] 2015-04-21 15:41
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment] 2015-04-25 18:52
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Closed by reek** 2015-04-25 18:52 UTC
Labels: Request
